version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: nest_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: taskdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
